### ISSUE TITLE
Does it support subsampling of large images?

### ISSUE THREAD

**Issue by emmauss** [seven332/android-gallery#1]
Does the library use use its own image view widget to show images? if so, does it support subsampling of large images?
Also can a .jar or .aar be released for this?

**Comment by seven332** [comment]
It supports subsampling of large images via [TiledDrawable](https://github.com/seven332/android-gallery/blob/8ef68aea8e0c8d0063a299ef0ac2d725746fd22b/gallery/src/main/java/com/hippo/android/gallery/drawable/TiledDrawable.java), not a view widget. The demo app use [Glide](https://github.com/bumptech/glide) to show images. Please read the source code if you want to know how to use this library with Glide.

You can get the .aar from JitPack. Please follow the instructions here.
https://jitpack.io/#seven332/android-gallery/e02d14420f

**Comment by emmauss** [comment]
thanks. your other libraries are great too.

**Comment by seven332** [comment]
This library is not well tested. So far I have not used this library in any actual app.

**Comment by emmauss** [comment]
tested out the demo. it was nice and smooth, and the options are good for a basic gallery implementation. does the gallery recycle out of sight views?

**Comment by seven332** [comment]
Yes, it does.
